return {
  -- { "vhyrro/luarocks.nvim", priority = 1000, config = true, },
  -- {
  --   "nvim-neorg/neorg",
  --   dependencies = { "luarocks.nvim" },
  --   lazy = false,
  --   version = "*",
  --   config = function()
  --     require('neorg').setup {
  --       load = {
  --           ["core.defaults"] = {},
  --           ["core.concealer"] = {},
  --           ["core.dirman"] = {
  --               config = {
  --                   workspaces = {
  --                       notes = "~/Workspace/notes",
  --                   },
  --                   default_workspace = "notes"
  --               }
  --           },
  --           ["core.journal"] = {
  --             config = {
  --                 workspace = "notes"
  --             }
  --         }
  --       }
  --     }
  --
  --   end,
  -- }
}
